name: Node.js CI
run-name: ${{ github.actor }} is testing the Teamwork API and Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DATABASE_URL: hello_family
  PORT: 3000
  TOKEN_SECRET: secret
  EMAIL_SERVICE_HOST: smtp.gmail.com
  EMAIL_SERVICE_PASSWORD: your host password
  EMAIL_SERVICE_PORT: 465
  EMAIL_SERVICE_USERNAME: example@gmail.com
  EMAIL_FROM: businessexample@gmail.com
  FRONTEND_BASE_URL: https://www.anyplaceholder.com/
  ORGANIZATION_NAME: teamwork

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test