name: Node.js CI
run-name: ${{ github.actor }} is testing the Teamwork API and Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PORT: ${{ secrets.PORT }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  EMAIL_SERVICE_HOST: ${{ secrets.EMAIL_SERVICE_HOST }}
  EMAIL_SERVICE_PASSWORD: ${{ secrets.EMAIL_SERVICE_PASSWORD }}
  EMAIL_SERVICE_PORT: ${{ secrets.EMAIL_SERVICE_PORT }}
  EMAIL_SERVICE_USERNAME: ${{ secrets.EMAIL_SERVICE_USERNAME }}
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
  FRONTEND_BASE_URL: ${{ secrets.FRONTEND_BASE_URL }}
  ORGANIZATION_NAME: ${{ secrets.ORGANIZATION_NAME }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test